routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
})->name('/');




// Guest Users
Route::middleware(['guest','PreventBackHistory'])->group(function()
{
    Route::get('login', [App\Http\Controllers\Admin\AuthController::class, 'showLogin'] )->name('login');
    Route::post('login', [App\Http\Controllers\Admin\AuthController::class, 'login'])->name('signin');
    Route::get('register', [App\Http\Controllers\Admin\AuthController::class, 'showRegister'] )->name('register');
    Route::post('registers', [App\Http\Controllers\Admin\AuthController::class, 'register'])->name('signup');

});


// Authenticated users
Route::middleware(['auth','PreventBackHistory'])->group(function()
{

    // Auth Routes
    Route::get('home', fn () => redirect()->route('dashboard'))->name('home');
    Route::get('dashboard', [App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('dashboard');
    Route::post('logout', [App\Http\Controllers\Admin\AuthController::class, 'Logout'])->name('logout');
    Route::get('change-theme-mode', [App\Http\Controllers\Admin\DashboardController::class, 'changeThemeMode'])->name('change-theme-mode');
    Route::get('show-change-password', [App\Http\Controllers\Admin\AuthController::class, 'showChangePassword'] )->name('show-change-password');
    Route::post('change-password', [App\Http\Controllers\Admin\AuthController::class, 'changePassword'] )->name('change-password');

    // Masters
    Route::resource('wards', App\Http\Controllers\Admin\Masters\WardController::class );
    Route::resource('category', App\Http\Controllers\Admin\Masters\CategoryController::class );
    Route::resource('scheme', App\Http\Controllers\Admin\Masters\SchemeController::class );
    Route::resource('document', App\Http\Controllers\Admin\Masters\DocumentController::class );
    Route::resource('financial', App\Http\Controllers\Admin\Masters\FinancialController::class );
    Route::resource('terms-conditions', App\Http\Controllers\Admin\Masters\TermsAndConditionsController::class );

    // User Panel
    Route::get('pdf_design', [App\Http\Controllers\Admin\Masters\DivyangController::class, 'pdf']);

    Route::get('terms_conditions/{id}', [App\Http\Controllers\Admin\DashboardController::class, 'terms_conditions'])->name('terms_conditions');
    Route::resource('hayatichaDakhlaform', App\Http\Controllers\Admin\Masters\DivyangController::class);
    Route::put('hayatichaDakhlaform/{id}/upload', [App\Http\Controllers\Admin\Masters\DivyangController::class, 'hayatuploadfile' ])->name('hayatichaDakhlaform.upload');

    Route::get('uploaded-document', [App\Http\Controllers\User\DivyangSchemeController::class, 'uploaded_doc']);
    // Divyang Scheme Application
    Route::resource('scheme_form', App\Http\Controllers\User\DivyangSchemeController::class);
    Route::get('divyang_certificate/{id}', [App\Http\Controllers\User\DivyangSchemeController::class, 'generateCertificate']);
    Route::get('divyang_view/{id}', [App\Http\Controllers\User\DivyangSchemeController::class, 'divyangRegistrationView']);
    Route::get('divyang_certificate_view/{id}', [App\Http\Controllers\User\DivyangSchemeController::class, 'divyangCertificate']);
    Route::get('divyang_application', [App\Http\Controllers\User\DivyangSchemeController::class, 'list'])->name('divyang.application');

    // Bus Concession Scheme Application
    Route::resource('bus_concession', App\Http\Controllers\User\BusConcessionSchemeController::class);
    Route::get('bus_concession_certificate/{id}', [App\Http\Controllers\User\BusConcessionSchemeController::class, 'generateCertificate']);
    Route::get('bus_concession_view/{id}', [App\Http\Controllers\User\BusConcessionSchemeController::class, 'busConcessionApplicationView']);
    Route::get('bus_concession_certificate_view/{id}', [App\Http\Controllers\User\BusConcessionSchemeController::class, 'busConcessionCertificate']);
    Route::get('bus_concession_application', [App\Http\Controllers\User\BusConcessionSchemeController::class, 'list'])->name('bus.concession.application');
    // Cancer Scheme Application
    Route::resource('cancer_scheme', App\Http\Controllers\User\CancerSchemeController::class);
    Route::get('cancer_certificate/{id}', [App\Http\Controllers\User\CancerSchemeController::class, 'generateCertificate']);
    Route::get('cancer_view/{id}', [App\Http\Controllers\User\CancerSchemeController::class, 'cancerSchemeApplicationView']);
    Route::get('cancer_scheme_certificate_view/{id}', [App\Http\Controllers\User\CancerSchemeController::class, 'cancerSchemeCertificate']);
    Route::get('cancer_scheme_application', [App\Http\Controllers\User\CancerSchemeController::class, 'list'])->name('cancer_scheme.application');
    // Education Scheme Application
    Route::resource('education_scheme', App\Http\Controllers\User\EducationSchemeController::class);
    Route::get('education_certificate/{id}', [App\Http\Controllers\User\EducationSchemeController::class, 'generateCertificate']);
    Route::get('education_view/{id}', [App\Http\Controllers\User\EducationSchemeController::class, 'eductationSchemeApplicationView']);
    Route::get('education_scheme_certificate_view/{id}', [App\Http\Controllers\User\EducationSchemeController::class, 'educationSchemeCertificate']);
    Route::get('education_scheme_application', [App\Http\Controllers\User\EducationSchemeController::class, 'list'])->name('education_scheme.application');
    // Marriage Scheme Application
    Route::resource('marriage_scheme', App\Http\Controllers\User\MarriageSchemeController::class);
    Route::get('marriage_certificate/{id}', [App\Http\Controllers\User\MarriageSchemeController::class, 'generateCertificate']);
    Route::get('marriage_view/{id}', [App\Http\Controllers\User\MarriageSchemeController::class, 'marriageSchemeApplicationView']);
    Route::get('marriage_scheme_application', [App\Http\Controllers\User\MarriageSchemeController::class, 'list'])->name('marriage_scheme.application');
    // Sports Scheme Application
    Route::resource('sports_scheme', App\Http\Controllers\User\SportsSchemeController::class);
    Route::get('sports_certificate/{id}', [App\Http\Controllers\User\SportsSchemeController::class, 'generateCertificate']);
    Route::get('sports_view/{id}', [App\Http\Controllers\User\SportsSchemeController::class, 'sportsSchemeApplicationView']);
    Route::get('sports_scheme_certificate_view/{id}', [App\Http\Controllers\User\SportsSchemeController::class, 'sportsSchemeCertificate']);
    Route::get('sports_scheme_application', [App\Http\Controllers\User\SportsSchemeController::class, 'list'])->name('sports_scheme.application');
    // Vehicle Scheme Application
    Route::resource('vehicle_scheme', App\Http\Controllers\User\VehicleSchemeController::class);
    Route::get('vehicle_certificate/{id}', [App\Http\Controllers\User\VehicleSchemeController::class, 'generateCertificate']);
    Route::get('vehicle_view/{id}', [App\Http\Controllers\User\VehicleSchemeController::class, 'vehicleSchemeApplicationView']);
    Route::get('vehicle_scheme_certificate_view/{id}', [App\Http\Controllers\User\VehicleSchemeController::class, 'vehicleSchemeCertificate']);
    Route::get('vehicle_scheme_application', [App\Http\Controllers\User\VehicleSchemeController::class, 'list'])->name('vehicle_scheme.application');
    // Women Sewing/Beautisians Scheme Application
    Route::resource('women_scheme', App\Http\Controllers\User\WomenSewingSchemeController::class);
    Route::get('women_certificate/{id}', [App\Http\Controllers\User\WomenSewingSchemeController::class, 'generateCertificate']);
    Route::get('women_view/{id}', [App\Http\Controllers\User\WomenSewingSchemeController::class, 'womenSchemeApplicationView']);
    Route::get('women_scheme_certificate_view/{id}', [App\Http\Controllers\User\WomenSewingSchemeController::class, 'womenSchemeCertificate']);
    Route::get('women_scheme_application', [App\Http\Controllers\User\WomenSewingSchemeController::class, 'list'])->name('women_scheme.application');

    // Hod Panel
    // Divyang Scheme Application
    Route::get('divyang_registration_list/{status}', [App\Http\Controllers\Hod\HodDivyangSchemeController::class, 'divyangRegistrationList']);
    Route::get('divyang_registration_view/{id}/{status}', [App\Http\Controllers\Hod\HodDivyangSchemeController::class, 'divyangRegistrationView']);
    Route::post('divyang_application_reject_by_hod/{id}', [App\Http\Controllers\Hod\HodDivyangSchemeController::class, 'rejectDivyangApplication']);
    Route::get('divyang_application_approve_by_hod/{id}', [App\Http\Controllers\Hod\HodDivyangSchemeController::class, 'approveDivyangApplication']);
    // Bus Concession Scheme Application
    Route::get('bus_concession_application_list/{status}', [App\Http\Controllers\Hod\HodBusConcessionSchemeController::class, 'busConcessionApplicationList']);
    Route::get('bus_concession_application_view/{id}/{status}', [App\Http\Controllers\Hod\HodBusConcessionSchemeController::class, 'busConcessionApplicationView']);
    Route::post('bus_concession_application_reject_by_hod/{id}', [App\Http\Controllers\Hod\HodBusConcessionSchemeController::class, 'rejectBusConcessionApplication']);
    Route::get('bus_concession_application_approve_by_hod/{id}', [App\Http\Controllers\Hod\HodBusConcessionSchemeController::class, 'approveBusConcessionApplication']);
    // Education Scheme Application

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Admin\Controller;
use App\Http\Requests\Admin\AssignUserRoleRequest;
use App\Http\Requests\Admin\ChangeUserPasswordRequest;
use App\Http\Requests\Admin\StoreUserRequest;
use App\Http\Requests\Admin\UpdateUserRequest;
use App\Models\Department;
use App\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use App\Models\User;
use App\Models\Ward;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $users = User::whereNot('id', Auth::user()->id)->latest()->get();
        $roles = Role::orderBy('id', 'DESC')->whereNot('name', 'like', '%super%')->get();

        return view('admin.users')->with(['users'=> $users, 'roles'=> $roles]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreUserRequest $request)
    {
        try
        {
            DB::beginTransaction();
            $input = $request->validated();
            $input['password'] = Hash::make($input['password']);
            $user = User::create( Arr::only( $input, Auth::user()->getFillable() ) );
            DB::table('model_has_roles')->insert(['role_id'=> $input['role'], 'model_type'=> 'App\Models\User', 'model_id'=> $user->id]);
            DB::commit();
            return response()->json(['success'=> 'User created successfully!']);
        }
        catch(\Exception $e)
        {
            return $this->respondWithAjax($e, 'creating', 'User');
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(User $user)
    {
        $roles = Role::whereNot('name', 'like', '%super%')->get();
        $user->loadMissing('roles');

        if ($user)
        {

            $roleHtml = '<span>
                <option value="">--Select Role --</option>';
                foreach($roles as $role):
                    $is_select = $role->id == $user->roles[0]->id ? "selected" : "";
                    $roleHtml .= '<option value="'.$role->id.'" '.$is_select.'>'.$role->name.'</option>';
                endforeach;
            $roleHtml .= '</span>';


            $response = [
                'result' => 1,
                'user' => $user,
                'roleHtml' => $roleHtml,
            ];
        }
        else
        {
            $response = ['result' => 0];
        }
        return $response;
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateUserRequest $request, User $user)
    {
        try
        {
            DB::beginTransaction();
            $input = $request->validated();
            $user->update( Arr::only( $input, Auth::user()->getFillable() ) );
            $user->roles()->detach();
            DB::table('model_has_roles')->insert(['role_id'=> $input['role'], 'model_type'=> 'App\Models\User', 'model_id'=> $user->id]);
            DB::commit();

            return response()->json(['success'=> 'User updated successfully!']);
        }
        catch(\Exception $e)
        {
            return $this->respondWithAjax($e, 'updating', 'User');
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }

    public function toggle(Request $request, User $user)
    {
        $current_status = DB::table('app_users')->where('id', $user->id)->value('active_status');
        try
        {
            DB::beginTransaction();
            if($current_status == '1')
            {
                User::where('id', $user->id)->update([ 'active_status' => '0' ]);
            }
            else
            {
                User::where('id', $user->id)->update([ 'active_status' => '1' ]);
            }
            DB::commit();
            return response()->json(['success'=> 'User status updated successfully']);
        }
        catch(\Exception $e)
        {
            return $this->respondWithAjax($e, 'changing', 'User\'s status');
        }
    }

    public function retire(Request $request, User $user)
    {
        try
        {
            DB::beginTransaction();
                $user->delete();
            DB::commit();
            return response()->json(['success'=> 'Employee retired successfully']);
        }
        catch(\Exception $e)
        {
            return $this->respondWithAjax($e, 'changing', 'Employee\'s retirement status');
        }
    }

    public function changePassword(ChangeUserPasswordRequest $request, User $user)
    {
        $input = $request->validated();
        try
        {
            DB::beginTransaction();
            $user->update([ 'password' => Hash::make($input['new_password']) ]);
            DB::commit();
            return response()->json(['success'=> 'Password updated successfully']);
        }
        catch(\Exception $e)
        {
            return $this->respondWithAjax($e, 'changing', 'User\'s password');
        }

    }


    public function getRole(User $user)
    {
        $user->load('roles');
        if ($user)
        {
            $roles = Role::orderBy('id', 'DESC')->get();
            $roleHtml = '<span>
                <option value="">--Select Role--</option>';
                foreach($roles as $role):
                    $is_select = $role->id == $user->roles[0]->id ? "selected" : "";
                    $roleHtml .= '<option value="'.$role->id.'" '.$is_select.'>'.$role->name.'</option>';
                endforeach;
            $roleHtml .= '</span>';

            $response = [
                'result' => 1,
                'user' => $user,
                'roleHtml' => $roleHtml,
            ];
        }
        else
        {
            $response = ['result' => 0];
        }
        return $response;
    }


    public function assignRole(User $user, AssignUserRoleRequest $request)
    {
        try
        {
            DB::beginTransaction();
            $user->roles()->detach();
            DB::table('model_has_roles')->insert(['role_id'=> $request->edit_role, 'model_type'=> 'App\Models\User', 'model_id'=> $user->id]);
            DB::commit();
            return response()->json(['success'=> 'Role updated successfully']);
        }
        catch(\Exception $e)
        {
            return $this->respondWithAjax($e, 'changing', 'User\'s role');
        }
    }




}

resources/views/users/education_scheme/education_scheme.blade.php
<x-admin.layout>
    <x-slot name="title">Education Scheme Form</x-slot>
    <x-slot name="heading">Education Scheme Form</x-slot>
    {{-- <x-slot name="subheading">Test</x-slot> --}}


        <!-- Add Form -->
        <div class="row" id="addContainer">
            <div class="col-sm-12">
                <div class="card">
                    <form class="theme-form"  name="addForm" id="addForm" enctype="multipart/form-data">
                        @csrf

                        <div class="card-header">
                            <h4 class="card-title">Add Education Scheme Form </h4>
                        </div>
                        <div class="card-body">
                            <div class="mb-3 row">
                                {{-- <input type="hidden" id="h_id" name="h_id" value=""> --}}

                                <div class="col-md-4 mt-3">
                                    <label class="col-form-label" for="name">संपूर्ण नाव</label>
                                    <input class="form-control"  type="text"  name="full_name"  value="" placeholder="Enter Full Name ">
                                    <span class="text-danger is-invalid full_name_err"></span>
                                </div>
                                <div class="col-md-4 mt-3">
                                    <label class="col-form-label" for="full_address">Full Address / संपूर्ण पत्ता</label>
                                    <input class="form-control"   type="text" name="full_address" value=""  placeholder="Enter Full Address">
                                    <span class="text-danger is-invalid full_address_err"></span>
                                </div>

                                <div class="col-md-4 mt-3">
                                    <label class="col-form-label" for="dob">Date Of Birth/ जन्म तारीख </label>
                                    <input class="form-control" id="dob" name="dob" type="date"  onchange="calculateAge()" placeholder="Enter Date Of Birth">
                                    <span class="text-danger is-invalid age_err"></span>
                                </div>

                                <div class="col-md-4 mt-3">
                                    <label class="col-form-label" for="Age"> Age/ वय </label>
                                    <input class="form-control" id="age" name="age" type="text"  placeholder="Enter Age">
                                    <span class="text-danger is-invalid age_err"></span>
                                </div>

                                <div class="col-md-4 mt-3">
                                    <label class="col-form-label" for="contact"> Mobile No/ मोबाईल क्र.:</label>
                                    <input class="form-control" id="contact" name="contact"  type="number"  placeholder="Enter Mobile No" min="0" onkeypress="return (event.charCode !=8 && event.charCode ==0 || (event.charCode >= 48 && event.charCode <= 57))">
                                    <span class="text-danger is-invalid contact_err"></span>
                                </div>

                                <div class="col-md-4 mt-3">
                                    <label class="col-form-label" for="email"> Email/ ई मेल आयडी:</label>
                                    <input class="form-control" id="email" name="email"  type="text"  placeholder="Enter Email" >
                                    <span class="text-danger is-invalid email_err"></span>
                                </div>

                                <div class="col-md-4 mt-3">
                                    <label class="col-form-label" for="beneficiary_relationship"> Beneficiary relationship/ लाभार्थ्याचे नाते :</label>
                                    <input class="form-control" id="beneficiary_relationship" name="beneficiary_relationship"  type="text"  placeholder="Enter Beneficiary relationship" >
                                    <span class="text-danger is-invalid beneficiary_relationship_err"></span>
                                </div>

                                <div class="col-md-4 mt-3">
                                    <label class="col-form-label" for="family_name">Name of Head of Family/ कूटुंब प्रमुखाचे नाव :</label>
                                    <input class="form-control" id="family_name" name="family_name"  type="text"  placeholder="Enter family name" >
                                    <span class="text-danger is-invalid family_name_err"></span>
                                </div>

                                <div class="col-md-4 mt-3">
                                    <label class="col-form-label" for="total_family">Total Number of Family / कुटुंबातील एकूण संख्या ::</label>
                                    <input class="form-control" id="total_family" name="total_family"  type="text"  placeholder="Enter total family" >
                                    <span class="text-danger is-invalid total_family_err"></span>
                                </div>


                                <div class="col-md-4 mt-3">
                                    <label class="col-form-label" for="adhaar_no">Aadhar Card Number  / आधारकार्ड क्रमांक <span class="text-danger">*</span></label>
                                    <input class="form-control" id="adhaar_no" name="adhaar_no" type="text" placeholder="Enter Adhaar Number">
                                    <span class="text-danger is-invalid adhaar_no_err"></span>
                                </div>

                                <div class="col-md-4 mt-3">
                                    <label class="col-form-label" for="candidate_signature">Upload Signature / thumb /अर्जदाराची सही / अगंठा</label>
                                    <input class="form-control" id="candidate_signature" name="candidate_signature" type="file" accept=".png, .jpg, .jpeg">
                                    <span class="text-danger is-invalid candidate_signature_err"></span>
                                </div>

                                <div class="col-md-4 mt-3">
                                    <label class="col-form-label" for="passport_size_photo">Passport Size Photo/अर्जदाराची फोटो</label>
                                    <input class="form-control" id="passport_size_photo" name="passport_size_photo" type="file" accept=".png, .jpg, .jpeg">
                                    <span class="text-danger is-invalid passport_size_photo_err"></span>
                                </div>


                                @foreach ($document as $doc)
                                <div class="col-md-4 mt-3">
                                        <label class="col-form-label" for="document_name">{{$doc->document_name}} @if($doc->is_required==1) <span class="required">*</span> @endif</label>
                                        <input type="hidden" name="document_id[]" class="form-control" value="{{$doc->id}}">
                                        <input type="file" name="document_file[]" class="form-control" multiple>
                                        <span class="text-danger is-invalid document_file_err"></span>
                                </div>
                            @endforeach

                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary" id="addSubmit">Submit</button>
                            <button type="reset" class="btn btn-warning">Reset</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>






</x-admin.layout>

<script>
    function calculateAge() {
        var dob = new Date(document.getElementById('dob').value);
        var today = new Date();
        var age = Math.floor((today - dob) / (365.25 * 24 * 60 * 60 * 1000));
        document.getElementById('age').value = age;
    }
</script>

{{-- Add --}}
<script>
    $("#addForm").submit(function(e) {
        e.preventDefault();
        $("#addSubmit").prop('disabled', true);

        var formdata = new FormData(this);
        $.ajax({
            url: '{{ route('education_scheme.store') }}',
            type: 'POST',
            data: formdata,
            contentType: false,
            processData: false,
            success: function(data)
            {
                $("#addSubmit").prop('disabled', false);
                if (!data.error2)
                    swal("Successful!", data.success, "success")
                        .then((action) => {
                            window.location.href = '{{ route('education_scheme.application') }}';
                        });
                else
                    swal("Error!", data.error2, "error");
            },
            statusCode: {
                422: function(responseObject, textStatus, jqXHR) {
                    $("#addSubmit").prop('disabled', false);
                    resetErrors();
                    printErrMsg(responseObject.responseJSON.errors);
                },
                500: function(responseObject, textStatus, errorThrown) {
                    $("#addSubmit").prop('disabled', false);
                    swal("Error occured!", "Something went wrong please try again", "error");
                }
            }
        });

        function resetErrors() {
            $('span.error-text').text('');
            $('input, select, textarea').removeClass('is-invalid');
        }

        function printErrMsg(msg) {
            $.each(msg, function(key, value) {
                $('.' + key + '_err').text(value);
                $('#' + key).addClass('is-invalid');
                $('#' + key).removeClass('is-valid');
            });
        }

    });


</script>