routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
})->name('/');




// Guest Users
Route::middleware(['guest','PreventBackHistory'])->group(function()
{
    Route::get('login', [App\Http\Controllers\Admin\AuthController::class, 'showLogin'] )->name('login');
    Route::post('login', [App\Http\Controllers\Admin\AuthController::class, 'login'])->name('signin');
    Route::get('register', [App\Http\Controllers\Admin\AuthController::class, 'showRegister'] )->name('register');
    Route::post('registers', [App\Http\Controllers\Admin\AuthController::class, 'register'])->name('signup');

});


// Authenticated users
Route::middleware(['auth','PreventBackHistory'])->group(function()
{

    // Auth Routes
    Route::get('home', fn () => redirect()->route('dashboard'))->name('home');
    Route::get('dashboard', [App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('dashboard');
    Route::post('logout', [App\Http\Controllers\Admin\AuthController::class, 'Logout'])->name('logout');
    Route::get('change-theme-mode', [App\Http\Controllers\Admin\DashboardController::class, 'changeThemeMode'])->name('change-theme-mode');
    Route::get('show-change-password', [App\Http\Controllers\Admin\AuthController::class, 'showChangePassword'] )->name('show-change-password');
    Route::post('change-password', [App\Http\Controllers\Admin\AuthController::class, 'changePassword'] )->name('change-password');

    // Masters
    Route::resource('wards', App\Http\Controllers\Admin\Masters\WardController::class );
    Route::resource('category', App\Http\Controllers\Admin\Masters\CategoryController::class );
    Route::resource('scheme', App\Http\Controllers\Admin\Masters\SchemeController::class );
    Route::resource('document', App\Http\Controllers\Admin\Masters\DocumentController::class );
    Route::resource('financial', App\Http\Controllers\Admin\Masters\FinancialController::class );
    Route::resource('terms-conditions', App\Http\Controllers\Admin\Masters\TermsAndConditionsController::class );

    // User Panel
    Route::get('pdf_design', [App\Http\Controllers\Admin\Masters\DivyangController::class, 'pdf']);

    Route::get('terms_conditions/{id}', [App\Http\Controllers\Admin\DashboardController::class, 'terms_conditions'])->name('terms_conditions');
    Route::resource('hayatichaDakhlaform', App\Http\Controllers\Admin\Masters\DivyangController::class);
    Route::put('hayatichaDakhlaform/{id}/upload', [App\Http\Controllers\Admin\Masters\DivyangController::class, 'hayatuploadfile' ])->name('hayatichaDakhlaform.upload');

    Route::get('uploaded-document', [App\Http\Controllers\User\DivyangSchemeController::class, 'uploaded_doc']);
    // Divyang Scheme Application
    Route::resource('scheme_form', App\Http\Controllers\User\DivyangSchemeController::class);
    Route::get('divyang_certificate/{id}', [App\Http\Controllers\User\DivyangSchemeController::class, 'generateCertificate']);
    Route::get('divyang_view/{id}', [App\Http\Controllers\User\DivyangSchemeController::class, 'divyangRegistrationView']);
    Route::get('divyang_certificate_view/{id}', [App\Http\Controllers\User\DivyangSchemeController::class, 'divyangCertificate']);
    Route::get('divyang_application', [App\Http\Controllers\User\DivyangSchemeController::class, 'list'])->name('divyang.application');

    // Bus Concession Scheme Application
    Route::resource('bus_concession', App\Http\Controllers\User\BusConcessionSchemeController::class);
    Route::get('bus_concession_certificate/{id}', [App\Http\Controllers\User\BusConcessionSchemeController::class, 'generateCertificate']);
    Route::get('bus_concession_view/{id}', [App\Http\Controllers\User\BusConcessionSchemeController::class, 'busConcessionApplicationView']);
    Route::get('bus_concession_certificate_view/{id}', [App\Http\Controllers\User\BusConcessionSchemeController::class, 'busConcessionCertificate']);
    Route::get('bus_concession_application', [App\Http\Controllers\User\BusConcessionSchemeController::class, 'list'])->name('bus.concession.application');
    // Cancer Scheme Application
    Route::resource('cancer_scheme', App\Http\Controllers\User\CancerSchemeController::class);
    Route::get('cancer_certificate/{id}', [App\Http\Controllers\User\CancerSchemeController::class, 'generateCertificate']);
    Route::get('cancer_view/{id}', [App\Http\Controllers\User\CancerSchemeController::class, 'cancerSchemeApplicationView']);
    Route::get('cancer_scheme_certificate_view/{id}', [App\Http\Controllers\User\CancerSchemeController::class, 'cancerSchemeCertificate']);
    Route::get('cancer_scheme_application', [App\Http\Controllers\User\CancerSchemeController::class, 'list'])->name('cancer_scheme.application');
    // Education Scheme Application
    Route::resource('education_scheme', App\Http\Controllers\User\EducationSchemeController::class);
    Route::get('education_certificate/{id}', [App\Http\Controllers\User\EducationSchemeController::class, 'generateCertificate']);
    Route::get('education_view/{id}', [App\Http\Controllers\User\EducationSchemeController::class, 'eductationSchemeApplicationView']);
    Route::get('education_scheme_certificate_view/{id}', [App\Http\Controllers\User\EducationSchemeController::class, 'educationSchemeCertificate']);
    Route::get('education_scheme_application', [App\Http\Controllers\User\EducationSchemeController::class, 'list'])->name('education_scheme.application');
    // Marriage Scheme Application
    Route::resource('marriage_scheme', App\Http\Controllers\User\MarriageSchemeController::class);
    Route::get('marriage_certificate/{id}', [App\Http\Controllers\User\MarriageSchemeController::class, 'generateCertificate']);
    Route::get('marriage_view/{id}', [App\Http\Controllers\User\MarriageSchemeController::class, 'marriageSchemeApplicationView']);
    Route::get('marriage_scheme_application', [App\Http\Controllers\User\MarriageSchemeController::class, 'list'])->name('marriage_scheme.application');
    // Sports Scheme Application
    Route::resource('sports_scheme', App\Http\Controllers\User\SportsSchemeController::class);
    Route::get('sports_certificate/{id}', [App\Http\Controllers\User\SportsSchemeController::class, 'generateCertificate']);
    Route::get('sports_view/{id}', [App\Http\Controllers\User\SportsSchemeController::class, 'sportsSchemeApplicationView']);
    Route::get('sports_scheme_certificate_view/{id}', [App\Http\Controllers\User\SportsSchemeController::class, 'sportsSchemeCertificate']);
    Route::get('sports_scheme_application', [App\Http\Controllers\User\SportsSchemeController::class, 'list'])->name('sports_scheme.application');
    // Vehicle Scheme Application
    Route::resource('vehicle_scheme', App\Http\Controllers\User\VehicleSchemeController::class);
    Route::get('vehicle_certificate/{id}', [App\Http\Controllers\User\VehicleSchemeController::class, 'generateCertificate']);
    Route::get('vehicle_view/{id}', [App\Http\Controllers\User\VehicleSchemeController::class, 'vehicleSchemeApplicationView']);
    Route::get('vehicle_scheme_certificate_view/{id}', [App\Http\Controllers\User\VehicleSchemeController::class, 'vehicleSchemeCertificate']);
    Route::get('vehicle_scheme_application', [App\Http\Controllers\User\VehicleSchemeController::class, 'list'])->name('vehicle_scheme.application');
    // Women Sewing/Beautisians Scheme Application
    Route::resource('women_scheme', App\Http\Controllers\User\WomenSewingSchemeController::class);
    Route::get('women_certificate/{id}', [App\Http\Controllers\User\WomenSewingSchemeController::class, 'generateCertificate']);
    Route::get('women_view/{id}', [App\Http\Controllers\User\WomenSewingSchemeController::class, 'womenSchemeApplicationView']);
    Route::get('women_scheme_certificate_view/{id}', [App\Http\Controllers\User\WomenSewingSchemeController::class, 'womenSchemeCertificate']);
    Route::get('women_scheme_application', [App\Http\Controllers\User\WomenSewingSchemeController::class, 'list'])->name('women_scheme.application');

    // Hod Panel
    // Divyang Scheme Application
    Route::get('divyang_registration_list/{status}', [App\Http\Controllers\Hod\HodDivyangSchemeController::class, 'divyangRegistrationList']);
    Route::get('divyang_registration_view/{id}/{status}', [App\Http\Controllers\Hod\HodDivyangSchemeController::class, 'divyangRegistrationView']);
    Route::post('divyang_application_reject_by_hod/{id}', [App\Http\Controllers\Hod\HodDivyangSchemeController::class, 'rejectDivyangApplication']);
    Route::get('divyang_application_approve_by_hod/{id}', [App\Http\Controllers\Hod\HodDivyangSchemeController::class, 'approveDivyangApplication']);
    // Bus Concession Scheme Application
    Route::get('bus_concession_application_list/{status}', [App\Http\Controllers\Hod\HodBusConcessionSchemeController::class, 'busConcessionApplicationList']);
    Route::get('bus_concession_application_view/{id}/{status}', [App\Http\Controllers\Hod\HodBusConcessionSchemeController::class, 'busConcessionApplicationView']);
    Route::post('bus_concession_application_reject_by_hod/{id}', [App\Http\Controllers\Hod\HodBusConcessionSchemeController::class, 'rejectBusConcessionApplication']);
    Route::get('bus_concession_application_approve_by_hod/{id}', [App\Http\Controllers\Hod\HodBusConcessionSchemeController::class, 'approveBusConcessionApplication']);
    // Education Scheme Application

app/Http/Controllers/Admin/Masters/CategoryController.php
<?php

namespace App\Http\Controllers\Admin\Masters;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Masters\StoreCategoryRequest;
use App\Http\Requests\Admin\Masters\UpdateCategoryRequest;
use Illuminate\Http\Request;
use App\Models\CategoryMst;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\DB;

class CategoryController extends Controller
{

    public function index()
    {
        $category = CategoryMst::latest()->get();
        return view('admin.masters.category')->with(['category'=> $category]);
    }


    public function store(StoreCategoryRequest $request)
    {
        try
        {
            DB::beginTransaction();
            $input = $request->validated();
            CategoryMst::create( Arr::only( $input, CategoryMst::getFillables() ) );
            DB::commit();
            return response()->json(['success'=> 'Category created successfully!']);
        }
        catch(\Exception $e)
        {
            return $this->respondWithAjax($e, 'creating', 'Category');
        }
    }


    public function edit(CategoryMst $category)
    {
        if ($category)
        {
            $response = [
                'result' => 1,
                'category' => $category,
            ];
        }
        else
        {
            $response = ['result' => 0];
        }
        return $response;

    }


    public function update(UpdateCategoryRequest $request, CategoryMst $category)
    {
        try
        {
            DB::beginTransaction();
            $input = $request->validated();
            $category->update( Arr::only( $input, CategoryMst::getFillables() ) );
            DB::commit();
            return response()->json(['success'=> 'Category updated successfully!']);
        }
        catch(\Exception $e)
        {
            return $this->respondWithAjax($e, 'updating', 'Category');
        }
    }


    public function destroy(CategoryMst $category)
    {
        try
        {
            DB::beginTransaction();
            $category->delete();
            DB::commit();
            return response()->json(['success'=> 'Category deleted successfully!']);
        }
        catch(\Exception $e)
        {
            return $this->respondWithAjax($e, 'deleting', 'Category');
        }
    }




}

app/Http/Controllers/Admin/Masters/DocumentController.php
<?php

namespace App\Http\Controllers\Admin\Masters;

use App\Http\Controllers\Admin\Controller;
use Illuminate\Http\Request;
use App\Models\DocumentMst;
use App\Models\SchemeMst;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\Admin\Masters\StoreDocumentRequest;
use App\Http\Requests\Admin\Masters\UpdateDocumentRequest;

class DocumentController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $documents = DocumentMst::latest()->get();

        $scheme = SchemeMst::latest()->get();
        return view('admin.masters.document')->with(['scheme'=> $scheme, 'documents'=>$documents]);
    }


    public function store(StoreDocumentRequest $request)
    {
        try
        {
            DB::beginTransaction();
            $input = $request->validated();
            DocumentMst::create(Arr::only($input, DocumentMst::getFillables()));
            DB::commit();
            return response()->json(['success'=> 'Document created successfully!']);
        }
        catch(\Exception $e)
        {
            return $this->respondWithAjax($e, 'creating', 'Document');
        }
    }


    public function edit(DocumentMst $document)
    {
        $scheme = SchemeMst::latest()->get();
        $document->load('scheme')->first();
        if ($document)
        {
            $schemeHtml = '<span>
            <option value="">--Select Scheme--</option>';
            foreach($scheme as $schemes):
                $is_select = $schemes->id == $document->scheme_id ? "selected" : "";
                $schemeHtml .= '<option value="'.$schemes->id.'" '.$is_select.'>'.$schemes->scheme_name.'</option>';
            endforeach;
            $schemeHtml .= '</span>';


            $response = [
                'result' => 1,
                'document' => $document,
                'schemeHtml'=>$schemeHtml
            ];
        }
        else
        {
            $response = ['result' => 0];
        }
        return $response;
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateDocumentRequest $request, DocumentMst $document)
    {
        try
        {
            DB::beginTransaction();
            $input = $request->validated();
            $input['scheme_id'] = $input['scheme_id'];
            $document->update( Arr::only( $input, DocumentMst::getFillables() ) );
            DB::commit();
            return response()->json(['success'=> 'Document updated successfully!']);
        }
        catch(\Exception $e)
        {
            return $this->respondWithAjax($e, 'updating', 'Document');
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(DocumentMst $document)
    {
        try
        {
            DB::beginTransaction();
            $document->delete();
            DB::commit();
            return response()->json(['success'=> 'Document deleted successfully!']);
        }
        catch(\Exception $e)
        {
            return $this->respondWithAjax($e, 'deleting', 'Document');
        }
    }
}

resources/views/admin/masters/category.blade.php
<x-admin.layout>
    <x-slot name="title">Categories</x-slot>
    <x-slot name="heading">Categories</x-slot>
    {{-- <x-slot name="subheading">Test</x-slot> --}}


        <!-- Add Form -->
        <div class="row" id="addContainer" style="display:none;">
            <div class="col-sm-12">
                <div class="card">
                    <form class="theme-form" name="addForm" id="addForm" enctype="multipart/form-data">
                        @csrf

                        <div class="card-header">
                            <h4 class="card-title">Add Category</h4>
                        </div>
                        <div class="card-body">
                            <div class="mb-3 row">
                                <div class="col-md-4">
                                    <label class="col-form-label" for="category_name">Category Name <span class="text-danger">*</span></label>
                                    <input class="form-control" id="category_name" name="category_name" type="text" placeholder="Enter Category Name">
                                    <span class="text-danger is-invalid category_name_err"></span>
                                </div>
                                <div class="col-md-4">
                                    <label class="col-form-label" for="initial">Initial <span class="text-danger">*</span></label>
                                    <input class="form-control" id="initial" name="initial" type="text" placeholder="Enter Category Initial">
                                    <span class="text-danger is-invalid initial_err"></span>
                                </div>
                            </div>

                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary" id="addSubmit">Submit</button>
                            <button type="reset" class="btn btn-warning">Reset</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>



        {{-- Edit Form --}}
        <div class="row" id="editContainer" style="display:none;">
            <div class="col">
                <form class="form-horizontal form-bordered" method="post" id="editForm">
                    @csrf
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Edit Category</h4>
                        </div>
                        <div class="card-body py-2">
                            <input type="hidden" id="edit_model_id" name="edit_model_id" value="">
                            <div class="mb-3 row">
                                <div class="col-md-4">
                                    <label class="col-form-label" for="category_name">Category Name <span class="text-danger">*</span></label>
                                    <input class="form-control" id="category_name" name="category_name" type="text" placeholder="Category Name">
                                    <span class="text-danger is-invalid category_name_err"></span>
                                </div>
                                <div class="col-md-4">
                                    <label class="col-form-label" for="initial">Initial <span class="text-danger">*</span></label>
                                    <input class="form-control" id="initial" name="initial" type="text" placeholder="Enter Category Initial">
                                    <span class="text-danger is-invalid initial_err"></span>
                                </div>
                            </div>

                        </div>
                        <div class="card-footer">
                            <button class="btn btn-primary" id="editSubmit">Submit</button>
                            <button type="reset" class="btn btn-warning">Reset</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>


        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="">
                                    <button id="addToTable" class="btn btn-primary">Add <i class="fa fa-plus"></i></button>
                                    <button id="btnCancel" class="btn btn-danger" style="display:none;">Cancel</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="buttons-datatables" class="table table-bordered nowrap align-middle" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Initial</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($category as $categories)
                                        <tr>
                                            <td>{{$categories->category_name}}</td>
                                            <td>{{$categories->initial}}</td>
                                            <td>
                                                <button class="edit-element btn text-secondary px-2 py-1" title="Edit category" data-id="{{ $categories->id }}"><i data-feather="edit"></i></button>
                                                <button class="btn text-danger rem-element px-2 py-1" title="Delete category" data-id="{{ $categories->id }}"><i data-feather="trash-2"></i> </button>
                                            </td>
                                        </tr>
                                    @endforeach
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>




</x-admin.layout>


{{-- Add --}}
<script>
    $("#addForm").submit(function(e) {
        e.preventDefault();
        $("#addSubmit").prop('disabled', true);

        var formdata = new FormData(this);
        $.ajax({
            url: '{{ route('category.store') }}',
            type: 'POST',
            data: formdata,
            contentType: false,
            processData: false,
            success: function(data)
            {
                $("#addSubmit").prop('disabled', false);
                if (!data.error2)
                    swal("Successful!", data.success, "success")
                        .then((action) => {
                            window.location.href = '{{ route('category.index') }}';
                        });
                else
                    swal("Error!", data.error2, "error");
            },
            statusCode: {
                422: function(responseObject, textStatus, jqXHR) {
                    $("#addSubmit").prop('disabled', false);
                    resetErrors();
                    printErrMsg(responseObject.responseJSON.errors);
                },
                500: function(responseObject, textStatus, errorThrown) {
                    $("#addSubmit").prop('disabled', false);
                    swal("Error occured!", "Something went wrong please try again", "error");
                }
            }
        });

        function resetErrors() {
            var form = document.getElementById('addForm');
            var data = new FormData(form);
            for (var [key, value] of data) {
                $('.' + key + '_err').text('');
                $('#' + key).removeClass('is-invalid');
                $('#' + key).addClass('is-valid');
            }
        }

        function printErrMsg(msg) {
            $.each(msg, function(key, value) {
                $('.' + key + '_err').text(value);
                $('#' + key).addClass('is-invalid');
                $('#' + key).removeClass('is-valid');
            });
        }

    });


</script>


<!-- Edit -->
<script>
    $("#buttons-datatables").on("click", ".edit-element", function(e) {
        e.preventDefault();
        var model_id = $(this).attr("data-id");
        var url = "{{ route('category.edit', ":model_id") }}";

        $.ajax({
            url: url.replace(':model_id', model_id),
            type: 'GET',
            data: {
                '_token': "{{ csrf_token() }}"
            },
            success: function(data, textStatus, jqXHR) {
                editFormBehaviour();
                if (!data.error)
                {
                    $("#editForm input[name='edit_model_id']").val(data.category.id);
                    $("#editForm input[name='category_name']").val(data.category.category_name);
                    $("#editForm input[name='initial']").val(data.category.initial);
                }
                else
                {
                    alert(data.error);
                }
            },
            error: function(error, jqXHR, textStatus, errorThrown) {
                alert("Some thing went wrong");
            },
        });
    });
</script>


<!-- Update -->
<script>
    $(document).ready(function() {
        $("#editForm").submit(function(e) {
            e.preventDefault();
            $("#editSubmit").prop('disabled', true);
            var formdata = new FormData(this);
            formdata.append('_method', 'PUT');
            var model_id = $('#edit_model_id').val();
            var url = "{{ route('category.update', ":model_id") }}";
            //
            $.ajax({
                url: url.replace(':model_id', model_id),
                type: 'POST',
                data: formdata,
                contentType: false,
                processData: false,
                success: function(data)
                {
                    $("#editSubmit").prop('disabled', false);
                    if (!data.error2)
                        swal("Successful!", data.success, "success")
                            .then((action) => {
                                window.location.href = '{{ route('category.index') }}';
                            });
                    else
                        swal("Error!", data.error2, "error");
                },
                statusCode: {
                    422: function(responseObject, textStatus, jqXHR) {
                        $("#editSubmit").prop('disabled', false);
                        resetErrors();
                        printErrMsg(responseObject.responseJSON.errors);
                    },
                    500: function(responseObject, textStatus, errorThrown) {
                        $("#editSubmit").prop('disabled', false);
                        swal("Error occured!", "Something went wrong please try again", "error");
                    }
                }
            });

        });
    });
</script>


<!-- Delete -->
<script>
    $("#buttons-datatables").on("click", ".rem-element", function(e) {
        e.preventDefault();
        swal({
            title: "Are you sure to delete this Category?",
            // text: "Make sure if you have filled Vendor details before proceeding further",
            icon: "info",
            buttons: ["Cancel", "Confirm"]
        })
        .then((justTransfer) =>
        {
            if (justTransfer)
            {
                var model_id = $(this).attr("data-id");
                var url = "{{ route('category.destroy', ":model_id") }}";

                $.ajax({
                    url: url.replace(':model_id', model_id),
                    type: 'POST',
                    data: {
                        '_method': "DELETE",
                        '_token': "{{ csrf_token() }}"
                    },
                    success: function(data, textStatus, jqXHR) {
                        if (!data.error && !data.error2) {
                            swal("Success!", data.success, "success")
                                .then((action) => {
                                    window.location.reload();
                                });
                        } else {
                            if (data.error) {
                                swal("Error!", data.error, "error");
                            } else {
                                swal("Error!", data.error2, "error");
                            }
                        }
                    },
                    error: function(error, jqXHR, textStatus, errorThrown) {
                        swal("Error!", "Something went wrong", "error");
                    },
                });
            }
        });
    });
</script>